# -*- coding: utf-8 -*-
"""ATCRAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q7xSD-xb_-3odQZwqYG4nTOJ1VZptvYx
"""

!tar -xvzf "/content/drive/MyDrive/ATCO2-ASRdataset-v1_beta.tgz" -C /content/drive/MyDrive/atco2_asr

!pip install faster-whisper pandas -q

from faster_whisper import WhisperModel
import pandas as pd
from pathlib import Path

# -----------------------------
# 1. 설정 (폴더 경로로 수정)
# -----------------------------
AUDIO_DIR = Path("/content/drive/MyDrive/atco2_asr")  # ← 폴더
OUTPUT_CSV = "/content/asr_output_folder.csv"

audio_exts = {".wav", ".mp3", ".m4a", ".flac", ".mp4"}

# -----------------------------
# 2. 모델 로드
# -----------------------------
model = WhisperModel("large-v3", device="cuda", compute_type="float16")

rows = []

# -----------------------------
# 3. 폴더 전체 처리
# -----------------------------
audio_files = list(AUDIO_DIR.rglob("*"))

print("총 파일 수:", len(audio_files))

for audio_file in audio_files:
    if audio_file.suffix.lower() not in audio_exts:
        continue

    print(f"Processing: {audio_file}")

    segments, info = model.transcribe(
        str(audio_file),
        beam_size=5,
        language="en",
        vad_filter=True
    )

    for i, seg in enumerate(segments):
        rows.append({
            "file": audio_file.name,
            "segment_id": i,
            "start": float(seg.start),
            "end": float(seg.end),
            "text": seg.text.strip(),
            "avg_logprob": getattr(seg, "avg_logprob", None),
            "language": info.language,
        })

# -----------------------------
# 4. CSV 저장
# -----------------------------
df = pd.DataFrame(rows)
df.to_csv(OUTPUT_CSV, index=False, encoding="utf-8-sig")

print("완료:", OUTPUT_CSV)
display(df.head())

!pip install faster-whisper pandas -q

from google.colab import files
from faster_whisper import WhisperModel
import pandas as pd
from pathlib import Path

# -----------------------------
# 1. 파일 직접 업로드
# -----------------------------
uploaded = files.upload()

audio_files = []
audio_exts = {".wav", ".mp3", ".m4a", ".flac", ".mp4", ".sph"}

for filename in uploaded.keys():
    path = Path(filename)
    if path.suffix.lower() in audio_exts:
        audio_files.append(path)

print("업로드된 음성/영상 파일 수:", len(audio_files))
print(audio_files)

# -----------------------------
# 2. 모델 로드
# -----------------------------
model = WhisperModel(
    "large-v3",
    device="cuda",        # GPU 사용 시 "cuda"
    compute_type="float16"  # GPU 사용 시 "float16"
)

# -----------------------------
# 3. 여러 파일 ASR 처리
# -----------------------------
rows = []

for audio_file in audio_files:
    print(f"Processing: {audio_file}")

    segments, info = model.transcribe(
        str(audio_file),
        beam_size=5,
        language="en",
        vad_filter=True,
        word_timestamps=False
    )

    for i, seg in enumerate(segments):
        rows.append({
            "file": audio_file.name,
            "segment_id": i,
            "start": float(seg.start),
            "end": float(seg.end),
            "text": seg.text.strip(),
            "avg_logprob": getattr(seg, "avg_logprob", None),
            "language": info.language,
            "language_probability": float(info.language_probability)
        })

# -----------------------------
# 4. CSV 저장 및 다운로드
# -----------------------------
df = pd.DataFrame(rows)

output_csv = "asr_output_all.csv"
df.to_csv(output_csv, index=False, encoding="utf-8-sig")

print("완료:", output_csv)
display(df.head())

files.download(output_csv)

"""### Gold annotation from XML"""

!mkdir -p /content/atco2_1h_xml

!mv /content/*.xml /content/atco2_1h_xml/

!ls /content/atco2_1h_xml | head

from pathlib import Path
xml_dir = Path("/content/atco2_1h_xml")

!ls /content

!tar -xvzf /content/drive/MyDrive/atco2_1h_xml-tar.gz -C /content/atco2_1h_xml

!find /content -name "*.xml" | head -20

import xml.etree.ElementTree as ET
import re
import pandas as pd
from pathlib import Path
from google.colab import files

xml_dir = Path("/content/atco2_1h_xml")  # ← 압축 푼 폴더

rows = []

for xml_file in xml_dir.rglob("*.xml"):
    tree = ET.parse(xml_file)
    root = tree.getroot()

    for i, seg in enumerate(root.findall(".//segment")):
        start = float(seg.find("start").text)
        end = float(seg.find("end").text)
        text = seg.find("text").text.strip()

        rows.append({
            "file": xml_file.name,
            "segment_id": i,
            "start": start,
            "end": end,
            "gold_text": text
        })

gold_df = pd.DataFrame(rows)

print("총 개수:", len(gold_df))
display(gold_df.head())

def remove_tags(text):
    text = re.sub(r'\[#.*?\]', '', text)
    text = re.sub(r'\[/#.*?\]', '', text)
    return text.strip()

gold_df["clean_text"] = gold_df["gold_text"].apply(remove_tags)

gold_df.to_csv("/content/atco2_gold_clean.csv", index=False, encoding="utf-8-sig")
files.download("/content/atco2_gold_clean.csv")

"""### gold-output 대조"""

import pandas as pd
import re
from pathlib import Path

# =========================
# 1. Load
# =========================
asr_df = pd.read_csv("/content/whisper_largev3_atc_output.csv")
gold_df = pd.read_csv("/content/atco2_gold_clean.csv")

asr_df.columns = asr_df.columns.str.strip()
gold_df.columns = gold_df.columns.str.strip()

print("ASR columns:", asr_df.columns.tolist())
print("GOLD columns:", gold_df.columns.tolist())

# =========================
# 2. file_key 생성
# =========================
asr_df["file_key"] = asr_df["file"].apply(lambda x: Path(str(x)).stem)

# gold 쪽 file 컬럼 자동 탐색
def find_gold_file_col(df):
    candidates = ["file", "filename", "file_name", "audio", "audio_file", "audio_path", "path", "wav", "wav_path"]
    for col in candidates:
        if col in df.columns:
            return col
    raise KeyError(f"Gold CSV에서 file 역할 컬럼을 찾지 못했습니다. 현재 컬럼: {df.columns.tolist()}")

gold_file_col = find_gold_file_col(gold_df)
gold_df["file_key"] = gold_df[gold_file_col].apply(lambda x: Path(str(x)).stem)

# =========================
# 3. Gold text 컬럼 자동 탐색
# =========================
def find_gold_text_col(df):
    candidates = ["gold_clean_text", "gold", "text", "transcript", "reference", "sentence"]
    for col in candidates:
        if col in df.columns:
            return col
    raise KeyError(f"Gold CSV에서 gold text 컬럼을 찾지 못했습니다. 현재 컬럼: {df.columns.tolist()}")

gold_text_col = find_gold_text_col(gold_df)

print("Detected gold file column:", gold_file_col)
print("Detected gold text column:", gold_text_col)

# =========================
# 4. Gold를 file 단위로 병합
# =========================
# start 컬럼이 있으면 시간순 정렬 후 병합
if "start" in gold_df.columns:
    gold_df["start"] = pd.to_numeric(gold_df["start"], errors="coerce")
    gold_df = gold_df.sort_values(["file_key", "start"])
else:
    gold_df = gold_df.sort_values(["file_key"])

gold_file_df = (
    gold_df
    .groupby("file_key", as_index=False)
    .agg({
        gold_text_col: lambda x: " ".join(x.fillna("").astype(str))
    })
    .rename(columns={gold_text_col: "gold"})
)

# =========================
# 5. ASR 정리
# =========================
asr_file_df = asr_df[["file_key", "file", "asr_text", "language", "language_probability", "empty_output", "error"]].copy()
asr_file_df = asr_file_df.rename(columns={"asr_text": "asr"})

# =========================
# 6. Gold-ASR file_key 기준 병합
# =========================
df = pd.merge(
    gold_file_df,
    asr_file_df,
    on="file_key",
    how="inner"
)

print("Matched files:", len(df))
print(df[["file_key", "gold", "asr"]].head())

# =========================
# 7. Normalization
# =========================
def normalize_text(text):
    if pd.isna(text):
        return ""
    text = str(text).lower()
    text = re.sub(r"\[[^\]]*\]", " ", text)      # [hes], [spk] 등 제거
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

# =========================
# 8. Edit distance
# =========================
def edit_distance(ref, hyp):
    n, m = len(ref), len(hyp)
    dp = [[0] * (m + 1) for _ in range(n + 1)]

    for i in range(n + 1):
        dp[i][0] = i

    for j in range(m + 1):
        dp[0][j] = j

    for i in range(1, n + 1):
        for j in range(1, m + 1):
            cost = 0 if ref[i - 1] == hyp[j - 1] else 1
            dp[i][j] = min(
                dp[i - 1][j] + 1,          # deletion
                dp[i][j - 1] + 1,          # insertion
                dp[i - 1][j - 1] + cost    # substitution
            )

    return dp[n][m]

def compute_wer(ref, hyp):
    ref_words = normalize_text(ref).split()
    hyp_words = normalize_text(hyp).split()

    dist = edit_distance(ref_words, hyp_words)
    n = len(ref_words)

    return dist / n if n > 0 else 0, dist, n

def compute_cer(ref, hyp):
    ref_chars = list(normalize_text(ref).replace(" ", ""))
    hyp_chars = list(normalize_text(hyp).replace(" ", ""))

    dist = edit_distance(ref_chars, hyp_chars)
    n = len(ref_chars)

    return dist / n if n > 0 else 0, dist, n

# =========================
# 9. Evaluation
# =========================
results = []

total_w_dist = 0
total_w_n = 0
total_c_dist = 0
total_c_n = 0

for _, row in df.iterrows():
    gold = row["gold"]
    asr = row["asr"]

    wer, w_dist, w_n = compute_wer(gold, asr)
    cer, c_dist, c_n = compute_cer(gold, asr)

    total_w_dist += w_dist
    total_w_n += w_n
    total_c_dist += c_dist
    total_c_n += c_n

    results.append({
        "file_key": row["file_key"],
        "file": row["file"],
        "gold": gold,
        "asr": asr,
        "WER": wer,
        "CER": cer,
        "language": row.get("language", ""),
        "language_probability": row.get("language_probability", ""),
        "empty_output": row.get("empty_output", ""),
        "error": row.get("error", "")
    })

result_df = pd.DataFrame(results)

corpus_wer = total_w_dist / total_w_n if total_w_n > 0 else 0
corpus_cer = total_c_dist / total_c_n if total_c_n > 0 else 0

print("\n===== File-level Corpus Evaluation =====")
print(f"Matched files: {len(result_df)}")
print(f"WER: {corpus_wer:.4f} ({corpus_wer * 100:.2f}%)")
print(f"CER: {corpus_cer:.4f} ({corpus_cer * 100:.2f}%)")

# =========================
# 10. Save
# =========================
output_path = "/content/wer_cer_file_level.csv"
result_df.to_csv(output_path, index=False, encoding="utf-8-sig")

print("Saved:", output_path)
result_df.head()

import pandas as pd
import re
from pathlib import Path

# =========================
# 1. Load data
# =========================
asr_df = pd.read_csv("/content/asr_output_folder.csv")
gold_df = pd.read_csv("/content/atco2_gold_clean.csv")

asr_df.columns = asr_df.columns.str.strip()
gold_df.columns = gold_df.columns.str.strip()

print("ASR columns:", asr_df.columns.tolist())
print("Gold columns:", gold_df.columns.tolist())

# =========================
# 2. file_key 생성
# =========================
asr_df["file_key"] = asr_df["file"].apply(lambda x: Path(str(x)).stem)
gold_df["file_key"] = gold_df["file"].apply(lambda x: Path(str(x)).stem)

# =========================
# 3. 시간순 정렬 후 file_key 단위로 문장 합치기
# =========================
asr_grouped = (
    asr_df
    .sort_values(["file_key", "start", "end"])
    .groupby("file_key")["text"]
    .apply(lambda x: " ".join(x.fillna("").astype(str)))
    .reset_index()
    .rename(columns={"text": "asr_text"})
)

gold_grouped = (
    gold_df
    .sort_values(["file_key", "start", "end"])
    .groupby("file_key")["gold_clean_text"]
    .apply(lambda x: " ".join(x.fillna("").astype(str)))
    .reset_index()
    .rename(columns={"gold_clean_text": "gold_text"})
)

# =========================
# 4. file_key 기준 merge
# =========================
df = pd.merge(
    gold_grouped,
    asr_grouped,
    on="file_key",
    how="inner"
)

print(f"Matched files: {len(df)}")
print(df.head())

# =========================
# 5. Text normalization
# =========================
def normalize_text(text):
    if pd.isna(text):
        return ""

    text = str(text).lower()

    # annotation tag 제거: [hes], [spk], [NE ...] 등
    text = re.sub(r"\[[^\]]*\]", " ", text)

    # punctuation 제거
    text = re.sub(r"[^a-z0-9\s]", " ", text)

    # 공백 정리
    text = re.sub(r"\s+", " ", text).strip()

    return text

# =========================
# 6. Edit distance
# =========================
def edit_distance(ref, hyp):
    n, m = len(ref), len(hyp)
    dp = [[0] * (m + 1) for _ in range(n + 1)]

    for i in range(n + 1):
        dp[i][0] = i
    for j in range(m + 1):
        dp[0][j] = j

    for i in range(1, n + 1):
        for j in range(1, m + 1):
            cost = 0 if ref[i - 1] == hyp[j - 1] else 1

            dp[i][j] = min(
                dp[i - 1][j] + 1,       # deletion
                dp[i][j - 1] + 1,       # insertion
                dp[i - 1][j - 1] + cost # substitution
            )

    return dp[n][m]

# =========================
# 7. WER / CER 계산 함수
# =========================
def compute_wer(ref, hyp):
    ref_words = normalize_text(ref).split()
    hyp_words = normalize_text(hyp).split()

    dist = edit_distance(ref_words, hyp_words)
    n = len(ref_words)

    return dist / n if n > 0 else 0, dist, n

def compute_cer(ref, hyp):
    ref_chars = list(normalize_text(ref).replace(" ", ""))
    hyp_chars = list(normalize_text(hyp).replace(" ", ""))

    dist = edit_distance(ref_chars, hyp_chars)
    n = len(ref_chars)

    return dist / n if n > 0 else 0, dist, n

# =========================
# 8. File-level evaluation
# =========================
results = []

total_w_dist = 0
total_w_n = 0
total_c_dist = 0
total_c_n = 0

for _, row in df.iterrows():
    gold = row["gold_text"]
    asr = row["asr_text"]

    wer, w_dist, w_n = compute_wer(gold, asr)
    cer, c_dist, c_n = compute_cer(gold, asr)

    total_w_dist += w_dist
    total_w_n += w_n
    total_c_dist += c_dist
    total_c_n += c_n

    results.append({
        "file_key": row["file_key"],
        "gold_text": gold,
        "asr_text": asr,
        "WER": wer,
        "CER": cer,
        "gold_word_count": w_n,
        "asr_word_count": len(normalize_text(asr).split())
    })

result_df = pd.DataFrame(results)

# =========================
# 9. Corpus-level result
# =========================
corpus_wer = total_w_dist / total_w_n if total_w_n > 0 else 0
corpus_cer = total_c_dist / total_c_n if total_c_n > 0 else 0

print("\n===== File-level Corpus Evaluation =====")
print(f"WER: {corpus_wer:.4f} ({corpus_wer * 100:.2f}%)")
print(f"CER: {corpus_cer:.4f} ({corpus_cer * 100:.2f}%)")

# =========================
# 10. Save
# =========================
output_path = "/content/wer_cer_file_level.csv"
result_df.to_csv(output_path, index=False, encoding="utf-8-sig")

print(f"\nSaved: {output_path}")

"""# 260504 ASR Finetuning"""

!pip install faster-whisper -q

from google.colab import drive
from pathlib import Path
import pandas as pd
from faster_whisper import WhisperModel

# =========================
# 0. Google Drive 마운트
# =========================
drive.mount('/content/drive')

# =========================
# 1. Drive 폴더에서 wav 파일 탐색
# =========================
DATA_DIR = Path(
    "/content/drive/MyDrive/ATC RAG/atco2_asr/ATCO2-ASRdataset-v1_beta/DATA"
)

audio_files = sorted([
    f for f in DATA_DIR.rglob("*")
    if f.suffix.lower() == ".wav"
])

print("Found wav files:", len(audio_files))

for f in audio_files:
    print(f)

# =========================
# 2. Whisper large-v3 로드
# =========================
model = WhisperModel(
    "large-v3",
    device="cuda",
    compute_type="float16"
)

# =========================
# 3. ATC prompt
# =========================
initial_prompt = """
Air traffic control radio communication.
Use aviation phraseology.
Common phrases include: good afternoon, radar contact, climb, descend, maintain,
heading, flight level, runway, airfield, ground, contact, squawk, approach.
Callsigns may contain words and numbers, for example Nav Checker Five One One.
"""

rows = []

for audio_path in audio_files:
    print("Processing:", audio_path.name)

    try:
        segments, info = model.transcribe(
            str(audio_path),
            language="en",
            task="transcribe",
            beam_size=5,
            best_of=5,
            temperature=0.0,
            vad_filter=False,
            condition_on_previous_text=False,
            initial_prompt=initial_prompt,
            word_timestamps=True
        )

        text = " ".join([seg.text.strip() for seg in segments]).strip()

        rows.append({
            "file_name": audio_path.name,
            "asr_text": text,
            "language": info.language,
            "language_probability": info.language_probability,
            "empty_output": text == "",
            "error": ""
        })

    except Exception as e:
        rows.append({
            "file_name": audio_path.name,
            "asr_text": "",
            "language": "",
            "language_probability": "",
            "empty_output": True,
            "error": str(e)
        })

df = pd.DataFrame(rows)
df.to_csv("/content/whisper_largev3_atc_output.csv", index=False, encoding="utf-8-sig")
df

"""WER CER 분석"""

result_df.sort_values("WER", ascending=False).head(20)

"""# RAG Pipeline

## phrase_units.jsonl
"""

phrase_units = [
    {
        "unit_id": "landing_clearance",
        "intent": "landing_clearance",
        "canonical_phrase": "[CALLSIGN] RUNWAY [RUNWAY] CLEARED TO LAND",
        "slots": ["CALLSIGN", "RUNWAY"],
        "trigger_keywords": ["runway", "cleared", "land", "cleared to land"],
        "common_asr_errors": [
            "cleared to land omitted",
            "runway retained but clearance command omitted",
            "callsign partially distorted",
            "runway left/right suffix omitted"
        ],
        "constraints": [
            "CLEARED TO LAND is safety-critical and must not be omitted if supported by context",
            "RUNWAY must be normalized to valid runway format",
            "Do not confuse landing clearance with takeoff clearance"
        ],
        "example_gold": [
            "runway one six right cleared to land Qantas Seventy Seven Zero One"
        ],
        "example_asr_error": [
            "Runway 16R"
        ],
        "priority": "high"
    },

    {
        "unit_id": "line_up_and_wait",
        "intent": "line_up_and_wait_clearance",
        "canonical_phrase": "[CALLSIGN] LINE UP RUNWAY [RUNWAY] AND WAIT",
        "slots": ["CALLSIGN", "RUNWAY"],
        "trigger_keywords": ["line up", "wait", "runway", "behind"],
        "common_asr_errors": [
            "and wait omitted",
            "runway number corrupted",
            "behind traffic condition omitted",
            "callsign confused with runway number"
        ],
        "constraints": [
            "LINE UP AND WAIT must not be converted into TAKE OFF clearance",
            "RUNWAY must be preserved",
            "BEHIND condition should be preserved if present"
        ],
        "example_gold": [
            "Swiss Three Three Two behind challenger line up to eight behind"
        ],
        "example_asr_error": [
            "This is 3-3-2 behind Challenger lineup 2-8 behind"
        ],
        "priority": "high"
    },

    {
        "unit_id": "taxi_instruction",
        "intent": "taxi_clearance",
        "canonical_phrase": "[CALLSIGN] TAXI VIA [TAXI_ROUTE]",
        "slots": ["CALLSIGN", "TAXI_ROUTE", "RUNWAY", "INTERSECTION"],
        "trigger_keywords": ["taxi", "via", "intersection", "holding point", "apron", "ground"],
        "common_asr_errors": [
            "taxi via misrecognized",
            "taxiway name distorted",
            "intersection name distorted",
            "QNH or runway number confused with route"
        ],
        "constraints": [
            "TAXI VIA must be followed by a valid taxi route or taxiway",
            "Taxi clearance must not be confused with airborne heading clearance",
            "Runway and intersection values should be normalized"
        ],
        "example_gold": [
            "Hotel Oscar QNH one zero three taxi three two intersection foxtrot"
        ],
        "example_asr_error": [
            "Cognite 1-0-2-3 taxi into 3-2 intersection Fox dot"
        ],
        "priority": "high"
    },

    {
        "unit_id": "frequency_transfer",
        "intent": "frequency_transfer",
        "canonical_phrase": "[CALLSIGN] CONTACT [FACILITY] [FREQUENCY]",
        "slots": ["CALLSIGN", "FACILITY", "FREQUENCY"],
        "trigger_keywords": ["contact", "tower", "ground", "approach", "radar", "decimal", "frequency"],
        "common_asr_errors": [
            "frequency number omitted",
            "decimal misrecognized",
            "facility name distorted",
            "callsign distorted"
        ],
        "constraints": [
            "FREQUENCY must be normalized, e.g., one two six decimal eight two five to 126.825",
            "FACILITY should be one of tower, ground, approach, radar, apron, delivery",
            "Do not confuse frequency transfer with frequency change approved"
        ],
        "example_gold": [
            "Nav Checker Five One One contact Sion approach one two six decimal eight two five"
        ],
        "example_asr_error": [
            "Smart Checkout 511 contact 26.825"
        ],
        "priority": "high"
    },

    {
        "unit_id": "frequency_change_approved",
        "intent": "frequency_change_approved",
        "canonical_phrase": "[CALLSIGN] FREQUENCY CHANGE APPROVED",
        "slots": ["CALLSIGN"],
        "trigger_keywords": ["frequency change", "approved", "good bye", "bye"],
        "common_asr_errors": [
            "frequency change approved misrecognized as frequency channel proof",
            "approved omitted",
            "callsign distorted",
            "goodbye repeated"
        ],
        "constraints": [
            "Do not insert a frequency value unless explicitly present",
            "Do not convert this into CONTACT FACILITY FREQUENCY",
            "GOOD BYE may be retained but is not operationally central"
        ],
        "example_gold": [
            "Hotel Golf Papa frequency change approved good bye"
        ],
        "example_asr_error": [
            "frequency channel proof goodbye"
        ],
        "priority": "medium"
    },

    {
        "unit_id": "squawk_instruction",
        "intent": "transponder_code_assignment",
        "canonical_phrase": "[CALLSIGN] SQUAWK [SQUAWK_CODE]",
        "slots": ["CALLSIGN", "SQUAWK_CODE"],
        "trigger_keywords": ["squawk", "transponder", "code", "seven thousand"],
        "common_asr_errors": [
            "squawk omitted",
            "four digit code partially recognized",
            "seven thousand misrecognized",
            "callsign distorted"
        ],
        "constraints": [
            "SQUAWK_CODE must be four digits",
            "Do not confuse squawk code with frequency, runway, or heading",
            "Code digits should be normalized from spoken form"
        ],
        "example_gold": [
            "Oscar Kilo Charlie Alfa Papa squawk seven thousand"
        ],
        "example_asr_error": [
            "Oscar kilo alpha papa seven thousand"
        ],
        "priority": "high"
    },

    {
        "unit_id": "heading_ils_approach",
        "intent": "approach_vectoring_clearance",
        "canonical_phrase": "[CALLSIGN] TURN [DIRECTION] HEADING [HEADING] CLEARED ILS APPROACH RUNWAY [RUNWAY] REPORT ESTABLISHED",
        "slots": ["CALLSIGN", "DIRECTION", "HEADING", "RUNWAY", "APPROACH_TYPE"],
        "trigger_keywords": ["turn", "heading", "left", "right", "ILS", "approach", "runway", "established"],
        "common_asr_errors": [
            "turn direction omitted",
            "heading number misrecognized",
            "cleared ILS approach shortened",
            "report established omitted"
        ],
        "constraints": [
            "HEADING must be a three-digit heading",
            "DIRECTION must be left or right",
            "RUNWAY must be valid",
            "CLEARED ILS APPROACH must not be reduced to generic approach text"
        ],
        "example_gold": [
            "Eurowings Seven Alfa Bravo turn right heading two one zero cleared ILS approach runway two four report established"
        ],
        "example_asr_error": [
            "EW7AB right heading 210 cleared ILS approach runway 24 report established"
        ],
        "priority": "high"
    },

    {
        "unit_id": "position_report_request",
        "intent": "position_report_request",
        "canonical_phrase": "[CALLSIGN] REPORT [POSITION]",
        "slots": ["CALLSIGN", "POSITION", "SEQUENCE"],
        "trigger_keywords": ["report", "final", "established", "base", "downwind", "number one", "number two"],
        "common_asr_errors": [
            "report final partially omitted",
            "report established omitted",
            "position word distorted",
            "callsign distorted"
        ],
        "constraints": [
            "REPORT FINAL is not landing clearance",
            "REPORT ESTABLISHED is not approach clearance by itself",
            "Traffic sequence such as number one or number two should be preserved"
        ],
        "example_gold": [
            "Echo X-ray number one report final"
        ],
        "example_asr_error": [
            "KXR1 report final"
        ],
        "priority": "medium"
    }
]

import json

output_path = "/content/phrase_units.jsonl"

with open(output_path, "w", encoding="utf-8") as f:
    for unit in phrase_units:
        f.write(json.dumps(unit, ensure_ascii=False) + "\n")

print("Saved:", output_path)

from google.colab import files
files.download("/content/phrase_units.jsonl")